# Funding platforms for Neuralift
# Uncomment and configure as needed

# github: [cr-nattress]
# patreon: neuralift
# open_collective: neuralift
# ko_fi: neuralift
# buy_me_a_coffee: neuralift
# custom: ['https://your-custom-link.com']
